### ISSUE TITLE
Add icon to this blog

### ISSUE THREAD

**Issue by onnhyd** [sceary-expert/Deyly#1]
Add Icon to this Blog. I am sharing the icon. Go to favicon.com then generate an icon and add that to this website so that this appear on top of the browser(where icon should be)
![apple-touch-icon](https://user-images.githubusercontent.com/84634405/182995737-762312fa-3595-4352-b745-cd929aa584ab.png)
.

**Comment by tsimian** [comment]
I forgot to say in the pull request, unrelated but I noticed you did not put your .env file in .gitignore. If you want to keep certain environment vars hidden you should add it.
